//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaBilgi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinemaBilgi.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string Beni_Hatırla {
            get {
                return ResourceManager.GetString("Beni Hatırla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Çıkış {
            get {
                return ResourceManager.GetString("Çıkış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçin.
        /// </summary>
        public static string Dil_Seçin {
            get {
                return ResourceManager.GetString("Dil Seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski Parola.
        /// </summary>
        public static string Eski_Parola {
            get {
                return ResourceManager.GetString("Eski Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmanlar.
        /// </summary>
        public static string Fragmanlar {
            get {
                return ResourceManager.GetString("Fragmanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string Giriş_Yap {
            get {
                return ResourceManager.GetString("Giriş Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftanın Filmleri.
        /// </summary>
        public static string Haftanın_Filmleri {
            get {
                return ResourceManager.GetString("Haftanın Filmleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınıza Giriş Yapın.
        /// </summary>
        public static string Hesabınıza_Giriş_Yapın {
            get {
                return ResourceManager.GetString("Hesabınıza Giriş Yapın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarları.
        /// </summary>
        public static string Hesap_Ayarları {
            get {
                return ResourceManager.GetString("Hesap Ayarları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarlarını Değiştir.
        /// </summary>
        public static string Hesap_Ayarlarını_Değiştir {
            get {
                return ResourceManager.GetString("Hesap Ayarlarını Değiştir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Yönetimi.
        /// </summary>
        public static string Hesap_Yönetimi {
            get {
                return ResourceManager.GetString("Hesap Yönetimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum Aç.
        /// </summary>
        public static string Oturum_Aç {
            get {
                return ResourceManager.GetString("Oturum Aç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncular.
        /// </summary>
        public static string Oyuncular {
            get {
                return ResourceManager.GetString("Oyuncular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola Değiştirme Formu.
        /// </summary>
        public static string Parola_Değiştirme_Formu {
            get {
                return ResourceManager.GetString("Parola Değiştirme Formu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolanı Değiştir.
        /// </summary>
        public static string Parolanı_Değiştir {
            get {
                return ResourceManager.GetString("Parolanı Değiştir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaryo.
        /// </summary>
        public static string Senaryo {
            get {
                return ResourceManager.GetString("Senaryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya.
        /// </summary>
        public static string Sosyal_Medya {
            get {
                return ResourceManager.GetString("Sosyal Medya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süre.
        /// </summary>
        public static string Süre {
            get {
                return ResourceManager.GetString("Süre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Parola.
        /// </summary>
        public static string Tekrar_Parola {
            get {
                return ResourceManager.GetString("Tekrar Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Yeni Parola.
        /// </summary>
        public static string Tekrar_Yeni_Parola {
            get {
                return ResourceManager.GetString("Tekrar Yeni Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür.
        /// </summary>
        public static string Tür {
            get {
                return ResourceManager.GetString("Tür", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string Üye_Ol {
            get {
                return ResourceManager.GetString("Üye Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyon Tarihi.
        /// </summary>
        public static string Vizyon_Tarihi {
            get {
                return ResourceManager.GetString("Vizyon Tarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyondakiler.
        /// </summary>
        public static string Vizyondakiler {
            get {
                return ResourceManager.GetString("Vizyondakiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakında.
        /// </summary>
        public static string Yakında {
            get {
                return ResourceManager.GetString("Yakında", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapım.
        /// </summary>
        public static string Yapım {
            get {
                return ResourceManager.GetString("Yapım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bir Hesap Oluştur.
        /// </summary>
        public static string Yeni_Bir_Hesap_Oluştur {
            get {
                return ResourceManager.GetString("Yeni Bir Hesap Oluştur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Parola.
        /// </summary>
        public static string Yeni_Parola {
            get {
                return ResourceManager.GetString("Yeni Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetmen.
        /// </summary>
        public static string Yönetmen {
            get {
                return ResourceManager.GetString("Yönetmen", resourceCulture);
            }
        }
    }
}
